version: 2

models:
  - name: int_orders__pivoted
    config:
      tags: ['pivot1']

  - name: customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: first_name #|| last_name
        tests:
          - unique:
              config:
                  store_failures: true  # always store failures
    config:
      materialized: view
      tags: ['cust']
      sql_header: -- From schema.yml
      

  - name: stg_customers
    config:
      tags: ['trig3']
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
